language: node_js
sudo: required
dist: trusty
node_js:
  - "8.9.3"
before_install: if [[ `npm -v` != 5.6.* ]]; then npm i -g npm@5.6; fi
matrix:
  fast_finish: true
services:
  - mongodb
  - docker
script: make travis
after_success:
  - nvm version
  - if [[ ! -z "$DOCKER_USER" ]]; then docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} && git checkout -- . && git clean -fd . && make docker_release; fi
after_script: make report
