name: Build Docker Image
on:
  push:
    branches:
      - upstream/wip/nspro/dev
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t nightscoutpro/cgm-remote-monitor:dev
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/cgm-remote-monitor:dev
